# Generated by Django 4.2.21 on 2025-06-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('snapshot_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='concepts.concept')),
            ],
            options={
                'ordering': ['-snapshot_at'],
            },
        ),
    ]
