# Generated by Django 4.2.23 on 2025-06-16 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0003_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('quest', 'Quest'), ('auth', 'Login/Signup'), ('profile', 'ProfileInput'), ('goal', 'GoalSet'), ('custom', 'Custom')], max_length=16)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('show_to_unauthenticated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
