# Generated by Django 4.2.23 on 2025-06-26 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Missionタイトル（自由記述 or 選択）', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Missionの詳細説明（任意）')),
                ('job', models.CharField(choices=[('tank', 'Tank（分析）'), ('healer', 'Healer（外交）'), ('mage', 'Mage（番人）'), ('assassin', 'Assassin（探検）')], max_length=16)),
                ('mbti', models.CharField(choices=[('INTJ', 'Architect（建築家）'), ('INTP', 'Logician（論理学者）'), ('ENTJ', 'Commander（指揮者）'), ('ENTP', 'Debater（討論者）'), ('INFJ', 'Advocate（提唱者）'), ('INFP', 'Mediator（仲介者）'), ('ENFJ', 'Protagonist（主人公）'), ('ENFP', 'Campaigner（運動家）'), ('ISTJ', 'Logistician（管理者）'), ('ISFJ', 'Defender（擁護者）'), ('ESTJ', 'Executive（領事）'), ('ESFJ', 'Consul（領事）'), ('ISTP', 'Virtuoso（巨匠）'), ('ISFP', 'Adventurer（冒険家）'), ('ESTP', 'Entrepreneur（起業家）'), ('ESFP', 'Entertainer（ESFP）')], max_length=8)),
                ('skill', models.CharField(choices=[('visionary', 'Visionary'), ('strategist', 'Strategist'), ('director', 'Director'), ('organizer', 'Organizer'), ('planner', 'Planner'), ('treasurer', 'Treasurer'), ('mediator', 'Mediator'), ('supporter', 'Supporter'), ('architect', 'Architect'), ('engineer', 'Engineer'), ('innovator', 'Innovator'), ('analyst', 'Analyst'), ('marketer', 'Marketer'), ('evangelist', 'Evangelist'), ('negotiator', 'Negotiator'), ('influencer', 'Influencer')], max_length=16)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
    ]
