# Generated by Django 4.2.23 on 2025-06-13 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='tags',
        ),
        migrations.AddField(
            model_name='quest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='QuestAchievement',
        ),
    ]
