# Generated by Django 4.2.23 on 2025-06-15 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='themes.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='themes.theme'),
        ),
        migrations.CreateModel(
            name='CrossThemeJobMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_job_maps', to='themes.job')),
                ('source_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_maps', to='themes.theme')),
                ('target_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_job_maps', to='themes.job')),
                ('target_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_maps', to='themes.theme')),
            ],
        ),
    ]
