# Generated by Django 4.2.21 on 2025-06-06 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_remove_concept_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('persona', 'Persona'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PersonaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_persistent', models.BooleanField(default=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_sessions', to='concepts.concept')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dialoguesession',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='dialoguesession',
            name='owner',
        ),
        migrations.DeleteModel(
            name='DialogueMessage',
        ),
        migrations.DeleteModel(
            name='DialogueSession',
        ),
        migrations.AddField(
            model_name='personamessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogues.personasession'),
        ),
    ]
