# Generated by Django 4.2.21 on 2025-06-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='persona_summary',
            field=models.TextField(blank=True),
        ),
    ]
