# Generated by Django 4.2.21 on 2025-06-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_concept_persona_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='summary',
        ),
    ]
