# Generated by Django 4.2.21 on 2025-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_concept_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
