# Generated by Django 4.2.21 on 2025-06-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_alter_concept_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={},
        ),
        migrations.RemoveField(
            model_name='concept',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='concept',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='cyan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='violet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='yellow',
            field=models.IntegerField(default=0),
        ),
    ]
