# Generated by Django 4.2.21 on 2025-06-09 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0006_alter_concept_options_remove_concept_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AddField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='slug',
            field=models.SlugField(default='sora', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
