# Generated by Django 4.2.21 on 2025-06-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0007_alter_concept_options_concept_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='cyan',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='green',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='orange',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='red',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='violet',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='yellow',
        ),
    ]
